name: CMO Mobile Backend - Build

on:
  workflow_dispatch:
    inputs:
      relordev:
        type: choice
        options: [Development, Release]
        default: Development
      relno:
        default: '1.0'
      branchName:
        default: develop
      buildimage:
        type: choice
        options: [Y, N]
        default: Y
      uploadimage:
        type: choice
        options: [Y, N]
        default: Y
      environment:
        default: local

jobs:
  call:
    uses: Mani242003/CCBT_GLOBAL_DEVOPS_WF/.github/workflows/cmo-mobile-backend-build.yml@main
    with:
      relordev: ${{ inputs.relordev }}
      relno: ${{ inputs.relno }}
      branchName: ${{ inputs.branchName }}
      buildimage: ${{ inputs.buildimage }}
      uploadimage: ${{ inputs.uploadimage }}
      environment: ${{ inputs.environment }}
      runner: ubuntu-latest
