name: Backend Build Entry

on:
  workflow_dispatch:
    inputs:
      relno:
        description: 'Release Number'
        required: true
        default: '1.0'   
      branchName:
        description: 'Branch Name'
        required: true
        default: develop


jobs:
  call-workflow:
    uses: Mani242003/CCBT_GLOBAL_DEVOPS_WF/.github/workflows/cmo-build.yml@main
    with:
      relno: ${{ inputs.relno }}
      branchName: ${{ inputs.branchName }}
      
